### ISSUE TITLE
Update Scala to 2.12

### ISSUE THREAD

**Issue by chetanmeh** [apache/incubator-openwhisk#3952]
Currently OpenWhisk uses Scala 2.11.11. We should switch to [Scala 2.12.6][1] which is current latest stable release. See [here][3] for details on all changes.

This change would require some coordination as we would need to move all other modules to move to Scala 2.12 at same time

## TODO

- [x] - `mesos-actor` needs to have a version based on 2.12
- [ ] - Create PR for all other modules which depend on core module

[1]: https://github.com/scala/scala/releases/tag/v2.12.6
[2]: https://github.com/scala/scala/releases/v2.12.0
[3]: https://www.scala-lang.org/news/2.12.0/

**Comment by chetanmeh** [comment]
Scala 2.12.7 provides a [10% speed improvement][1]

> Scala 2.12.7 is now available, **bringing another 10% improvement** in compiler performance, markdown tables in Scaladoc, improved Java 11 support, and Spark 2.4 compatibility!

[1]: https://www.scala-lang.org/news/2.12.7

**Comment by chetanmeh** [comment]
Following repos would need to be modified 

- [ ] [incubator-openwhisk-runtime-java](https://github.com/apache/incubator-openwhisk-runtime-java)  
- [ ] [incubator-openwhisk-runtime-swift](https://github.com/apache/incubator-openwhisk-runtime-swift)  
- [ ] [incubator-openwhisk-runtime-php](https://github.com/apache/incubator-openwhisk-runtime-php)   
- [ ] [incubator-openwhisk-runtime-nodejs](https://github.com/apache/incubator-openwhisk-runtime-nodejs) 
- [ ] [incubator-openwhisk-runtime-python](https://github.com/apache/incubator-openwhisk-runtime-python) 
- [ ] [incubator-openwhisk-runtime-docker](https://github.com/apache/incubator-openwhisk-runtime-docker) 
- [ ] [incubator-openwhisk-runtime-ruby](https://github.com/apache/incubator-openwhisk-runtime-ruby) 
- [ ] [incubator-openwhisk-runtime-ballerina](https://github.com/apache/incubator-openwhisk-runtime-ballerina) 

- [ ] [incubator-openwhisk-catalog](https://github.com/apache/incubator-openwhisk-catalog)
- [ ] [incubator-openwhisk-cli](https://github.com/apache/incubator-openwhisk-cli)
- [ ] [incubator-openwhisk-package-deploy](https://github.com/apache/incubator-openwhisk-package-deploy) 
- [ ] [incubator-openwhisk-package-alarms](https://github.com/apache/incubator-openwhisk-package-alarms)
- [ ] [incubator-openwhisk-package-cloudant](https://github.com/apache/incubator-openwhisk-package-cloudant)
- [ ] [incubator-openwhisk-package-kafka](https://github.com/apache/incubator-openwhisk-package-kafka)

**Comment by chetanmeh** [comment]
All PRs now merged!
